### ISSUE TITLE
Warning: all the old depndecies make this game hard to run in 2023 never got it running

### ISSUE THREAD

**Issue by YukiTrace** [design1online/WTF-Adventure#100]
figuring out how to get the right version of node maybe it was 14  I think, mysql 5.7 something, and other dependencies was hard in 2023. I found myself for whatever reason (sorry this was a couple days ago) running old 20.04 Ubuntu and running an MySQL in docker because it wouldn't work on that version of OS but some other thing needed that version of the OS. Also you need a gui and a web browser to make the server run :(. Which is a waste ram/money imo for running one of these servers long term. Couldn't get x11 working or many other workarounds to spoof gui. running a browser. I think after much too time spent I could have got it working with a gui probably but gave up. If you are trying to get this running I got close but would not recommend. I don't know if this is bad form on GitHub or not I'm new here. To recommend a fork I never was able to play this game and see what makes it unique. I spend two days on it. I was however able to get https://github.com/Kaetram/Kaetram-Open working another fork of tap tap adventure and browser quest I wish I knew about sooner. That game I got working in like half a day when skipping the database and little more time polishing thing in like a day.Based on the print outs from the server that I saw in both versions like entities spawned and other numbers I saw my guess is that game is more feature complete.  

Consider taking the best features of this and rolling it into that fork if you are still passionate about this game. Or make a docker container to make running it easy and posting it on one of those container sites to preserve it. Or maybe you moved on. I wondered why it was called WTF Adventure :) I hope I didn't come off as too rude. It was just my first time having a hell of a time with old software and dependencies on Ubuntu and I needed to vent. I bet I would have liked you game if I could have got it running. I'm glad to see another woman wanting to get girls into tech stuff.

**Comment by design1online** [comment]
Hey there, thanks for the feedback. I'm planning to update all dependencies during hacktober fest. This branch isn't well aligned with Kaetram-Open anymore because everything has been upgraded to es6. I know at one point in time he was working on upgrading his as well but I haven't checked if he has in quite a while.

If you can give me your docker snapshot I can include that in the readme for anyone using it.

**Comment by design1online** [comment]
Converted to use nextJs
