### ISSUE TITLE
Client doesnt work

### ISSUE THREAD

**Issue by Pelix87** [design1online/WTF-Adventure#12]
- its not possible to enter text in the input (so registriation or login not possible)

- click on Guest login crashed the server:
`/home/browsergame/src/server/js/game/world.js:802
      if (entity.instance in this.MobsDictionary) {
                          ^

TypeError: Cannot use 'in' operator to search for '1101' in undefined`

**Comment by design1online** [comment]
I updated the dictionaries back to their old format since the classes were not working for them.
