### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by Pelix87** [design1online/WTF-Adventure#13]
its not possible to insert text in login and register inputs

after click on "Guest login" the server crash with error:

 _this.mobsDictionary = new _mobs.default();
                           ^

TypeError: _mobs.default is not a constructor
    at Player.Character (/home/browsergame/src/server/js/game/entity/character/character.js:43:27)
    at new Player (/home/browsergame/src/server/js/game/entity/character/player/player.js:31:5)
    at World.playerConnectCallback (/home/browsergame/src/server/js/game/world.js:54:22)
    at Server.playerConnectCallback [as connectionCallback] (/home/browsergame/src/server/js/main.js:107:22)
    at Socket.connectionCallback (/home/browsergame/src/server/js/network/websocket.js:88:16)
    at Socket.emit (events.js:189:13)
    at /home/browsergame/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by dmidex** [comment]
Same problem

**Comment by mutatedplague** [comment]
Same issue any fix yet?

**Comment by Veradictus** [comment]
Seems like an ES6 malformation error.
I am the original developer of this code, I highly suggest checking out the original. Development has resumed: https://github.com/Veradictus/Kaetram-Open

**Comment by Slluxx** [comment]
@Veradictus instead of referring back to your engine, i am pretty sure we all would appreciate a pull request. 

also @design1online could you please take a look at this? this problem is present since march and if you have no interest in maintaining this, at least bring it into a working state or remove the project entirely. There is enough broken code on GitHub.

**Comment by Veradictus** [comment]
@Slluxx As I stated, it seems as the entire engine is wrongly and/or incompletely converted to ES6. How am I supposed to provide a pull request when the issue could be the entirety of the codebase?

**Comment by design1online** [comment]
This was an issue with the ES6 conversion and difference in how `this` is scoped in ES6 that didn't translate well from the legacy code. Your particular issue has been fixed however there are some more ES6 errors that are being worked out (mouse move and click event handlers not always firing, not drawing NPC characters). Thanks for your patience. If you don't want to wait for the fixes feel free to fork from Tap Tap Adventure and do your own ES6/webpack conversion.
