### ISSUE TITLE
sanırsam mysql server mysql a baglanmıyor

### ISSUE THREAD

**Issue by Kyavuzer** [design1online/WTF-Adventure#37]
![image](https://user-images.githubusercontent.com/37276141/93716344-c80cc880-fb5e-11ea-8919-6d7aab182503.png)

**Comment by Veradictus** [comment]
There's an error in your config.

**Comment by EfeYavuzer** [comment]
@Veradictus config.json 
![image](https://user-images.githubusercontent.com/37276141/93718327-e973b180-fb6a-11ea-982b-bf3f43f5f173.png)

**Comment by Veradictus** [comment]
`"host": "localhost`

Should be


`"host": "localhost"`

**Comment by EfeYavuzer** [comment]
@Veradictus 
![image](https://user-images.githubusercontent.com/37276141/93719151-445bd780-fb70-11ea-9b9c-a9db0f7e83ca.png)

**Comment by Veradictus** [comment]
Use `127.0.0.1` and port 9000

**Comment by EfeYavuzer** [comment]
@Veradictus

**Comment by EfeYavuzer** [comment]
@Veradictus 
![image](https://user-images.githubusercontent.com/37276141/93719399-d57f7e00-fb71-11ea-9706-abb17802a9ea.png)

**Comment by EfeYavuzer** [comment]
![image](https://user-images.githubusercontent.com/37276141/93719409-df08e600-fb71-11ea-9c55-659ab316fb40.png)
@Veradictus

**Comment by EfeYavuzer** [comment]
![image](https://user-images.githubusercontent.com/37276141/93719911-2e044a80-fb75-11ea-8dfd-2495b166235b.png)
@Veradictus

**Comment by EfeYavuzer** [comment]
@Veradictus ??

**Comment by Veradictus** [comment]
You need to do some research before trying to set up this. I can't just set it up for you. Please see https://github.com/Kaetram/Kaetram-Open if you want a more stable version.

**Comment by design1online** [comment]
@Kyavuzer it looks like you didn't create the mysql database or it doesn't have sufficient permissions with the user/password that you gave it to create the database tables that it needs to. All of the SQL that's required to create the database tables is located in src/server/js/database/creator.js

**Comment by xxmartinxx1** [comment]
First check if you have socket.io installed

`NPM install socket.io

The 99% error is because you don't have the module installed


For me working very but 

![1](https://user-images.githubusercontent.com/44817506/149670298-493838cc-c872-4835-a268-5c302de207fc.png)

```
Config.json

`{
  "name": "WTF?! Adventure",
  "host": "0.0.0.0",
  "port": 8081,

  "offlineMode": false,
  "devClient": false,
  "development": false,
  "overrideAuth": false,

  "mysqlHost": "localhost",
  "mysqlPort": 3306,
  "mysqlUser": "root",
  "mysqlPassword": "",
  "mysqlDatabase": "test",

  "debugLevel": "info",
  "localDebug": false,
  "worlds": 1,
  "maxPlayers": 5,
  "gver": 3,
  "updateTime": 200,

  "secretKey": "",

  "forceCollisions": false
}
```

**Comment by xxmartinxx1** [comment]
![1](https://user-images.githubusercontent.com/44817506/149670351-ac594b58-6958-47e8-b782-0b6feb16f123.png)

Check this module :)
